### ISSUE TITLE
page report

### ISSUE THREAD

**Issue by Lusoraca** [venus-ai-team/front-end#15]
A problem happened to me, the bot's responses do not load, an x ​​appears above the bot's name, I already tried to restart it but it gives me the same result.
(my apologies if any of what I wrote is confusing, I'm a Latin speaker and I don't know that much English)

Thank you very much for your attention 
-piri
![1684207583774](https://github.com/venus-ai-team/front-end/assets/133731819/c481977d-1723-43df-9f16-b5cc180d2396)

**Comment by nilitaa** [comment]
The same thing is happening to me, the bot doesn't give me a single answer and I get that little cross mark at the top😕

**Comment by yumixpeach** [comment]
Everytime I tried to send a message it always shows this.
![Uploading Screenshot_20230518-144231_1.jpg…]()

**Comment by Xuri-9** [comment]
I have the same thing too, idk wut to do
