### ISSUE TITLE
Exceeded quota?

### ISSUE THREAD

**Issue by Mchngrl** [venus-ai-team/front-end#18]
When I want to talk to a bot I get this, the site is free, right?

![Screenshot_20230521-084048_Chrome](https://github.com/venus-ai-team/front-end/assets/134212564/0f3003f5-7d09-45f0-8251-b880e7e78914)

**Comment by Mchngrl** [comment]
Ty

**Comment by welovecassandra** [comment]
What do I do If I have the same problem?
