### ISSUE TITLE
Chars disappear

### ISSUE THREAD

**Issue by Kumo111** [venus-ai-team/front-end#4]
My chars disappear from my char page, but  chats still here. And new characters, even only with word "test" in, do not appear. 
![IMG_20230505_210359](https://user-images.githubusercontent.com/132701253/236534932-747ab1bd-e4ac-4044-980f-50dd73bb7cb6.jpg)
![IMG_20230505_210309](https://user-images.githubusercontent.com/132701253/236534938-81cfb21c-2a4c-4545-aa73-87b871427c25.jpg)

**Comment by harry-pham-wise** [comment]
Yax seems to be a bug, let me fix :D

**Comment by conanak99** [comment]
Just fixed now, please refresh the page.  thank for reporting :D
