### ISSUE TITLE
Response from Character AI

### ISSUE THREAD

**Issue by PDooru** [venus-ai-team/front-end#5]
I was messing around with the AI response and suddenly all the response is related to Joker smashing my character's head against a pencil????????

I thought it was the issue with the story at first but when it restarted the entire conversation joker appears again???? And not just this character, across every other character as well. Like wth-

It was working just fine like 10 minutes before, before Joker decided to cross the multiverse and kill me again and again-

How do i fix this????? Idk if i should laugh or cry at this point-

Legit this is not a joke.
![image_2023-05-07_022414944](https://user-images.githubusercontent.com/132779866/236640758-5ea30c25-3045-45bb-b464-788f8001758b.png)
![image_2023-05-07_022516110](https://user-images.githubusercontent.com/132779866/236640802-92c361d6-fd75-4adc-9656-3153bd295e1b.png)
![image_2023-05-07_022811537](https://user-images.githubusercontent.com/132779866/236640940-02ebc41e-86db-4ab7-8dda-ddee53f62d7e.png)

**Comment by conanak99** [comment]
Please use your own API keys. Reverse proxy can be tempered and logged.
