### ISSUE TITLE
Failed to fetch 

### ISSUE THREAD

**Issue by Keito69** [venus-ai-team/front-end#6]
it seems i cannot use this, my networks seems working well and i cannot use it to my desires ;-;. i want to rp-

![chrome_screenshot_1683421266850](https://user-images.githubusercontent.com/132794008/236652494-5730eec2-8291-4ea3-84f3-7356c971d6aa.png)

**Comment by conanak99** [comment]
Please use your own key, reverse proxy is unusable now.

**Comment by Shyndymu** [comment]
> Utilice su propia clave, el proxy inverso no se puede utilizar ahora.

How can I remove the Proxy API?
